#!/bin/bash
set -e

if [ "$#" -lt 2 ]
then
	echo "usage: swiftwasm file1.swift file2.swift.... output.wasm"
	exit 1
fi
sdk="$(dirname $0)"
echo "$sdk"
tmpobj="$(mktemp -t swiftwasm)"
outputfile="${@: -1}"
if [[ "$outputfile" != *.wasm ]]
then
	echo "output should end in .wasm"
	exit 1
fi
sysroot="$(dirname $0)/wasi-sdk/opt/wasi-sdk/share/sysroot"

"$sdk/extra_utils/generateModuleMap.sh" >"$sdk/opt/swiftwasm-sdk/lib/swift/wasm/wasm32/glibc.modulemap"

"$sdk/opt/swiftwasm-sdk/bin/swiftc" -target wasm32-unknown-unknown-wasm \
	-sdk "$sysroot" -O -c \
	-o "$tmpobj" \
	"${@:1:$#-1}"
"$sdk/wasi-sdk/opt/wasi-sdk/bin/wasm-ld" --error-limit=0 -o "$outputfile" \
	"$sysroot/lib/wasm32-wasi/crt1.o" \
	"$sdk/extra_objs/swift_start.o" \
	"$sdk/opt/swiftwasm-sdk/lib/swift_static/wasm/wasm32/swiftrt.o" \
	"$tmpobj" \
	"-L$sdk/opt/swiftwasm-sdk/lib/swift_static/wasm" \
	"-L$sysroot/lib/wasm32-wasi" \
	"-L$sdk/icu_out/lib" \
	-lswiftCore \
	-lc -lc++ -lc++abi -lswiftImageInspectionShared \
	-licuuc -licudata \
	"$sdk/wasi-sdk/opt/wasi-sdk/lib/clang/8.0.0/lib/wasi/libclang_rt.builtins-wasm32.a" \
	"$sdk/extra_objs/fakepthread.o" \
	"$sdk/extra_objs/fakelocaltime.o" \
	"$sdk/extra_objs/swift_end.o" \
	--no-gc-sections
rm "$tmpobj"
